# In this notebook, we're going to cover some of the most fundermental concepts of tensors using TensorFlow

More specifically, we;re going to cover,
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs whit TensorFlow (or TPUs)
* Exercises to try for yourself!

## Introduction to Tensors 

In [2]:
# Improt TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                        [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                                [3., 2.],
                                [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# What do you think the dimension of another_matrix will be?
another_matrix.ndim

2

In [14]:
# Let's craate a tensor
tensor = tf.constant([[[1, 2, 3],
                        [4, 5, 6]],
                        [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
tensor.ndim

3

What we've create so far:

* Scalar: a single number
* Vector: a number with direction(eg. wind speed direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimentional array of numbers (when n acan be any number, a 0-dimentional tensor is a scalar, a 1-dimentional tensor is a vector)

### Creating Tensors with `tf.Variable()`

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).

In [28]:
# Create the same tensor with tf.variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

Now let's try to change one of the elements of the changable tensor.

### Create random Tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [29]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [20]:
# Create  two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [23]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [27]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # will produce the same shuffled tensor every time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Other ways to make tensors

In [30]:
# Make a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [31]:
# Make a tensor of all zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A, shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

## Getting information from tensors(shape, rank, size)

* **Shape** The length (number of elements) of each of the dimensions of a tensor.
* **Rank** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis** or **Dimension:** A particular dimension of a tensor.
* **Size:** The total number of items in the tensor.

In [34]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [42]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


In [43]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [45]:
# Get the dimension from each index except fro the final one
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [46]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

You can also add dimensions to your tensor while keeping the same information present using `tf,newaxis`

In [47]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] #in python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2) shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

You can do same thing using `tf.expand_dims()`

In [48]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

## Manipulating tensors (tensor operations)

Finding pattens in tensors (numberical representaion of data) requires manipulating them.

Again, when building models in TensorFlow, much of this patten discovery is done for you.

### Basic operations

In [54]:
tensor = tf.constant([[10, 7], [3, 4]])
print("tensor + 10")
tensor + 10

tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [51]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [55]:
# Multiplication also works
print("tensor * 10")
tensor * 10

tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [56]:
# Subtraction
print("tensor - 10")
tensor  - 10

tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

You can also us the TensorFlow fuctions.

In [57]:
# Use the tensorflow function equivalent to the numpy function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

### Matrix Mutliplicatin

One of most common operations in machine learning algoritham is `matrix multiplication`.

TensorFlow functionality is `tf.matmul()` method.

The Two main rules of matrix multiplication are:
1. The inner dimentsions must match:
* `(3, 5) @ (3, 5)` won't work
* `(5, 3) @ (3, 5)` will work
* `(3, 5) @ (5, 3)` will work
2. The resulting matrix has the shape of the outer dimentsions:
* `(5, 3) @ (3, 5)` -> `(5, 5)`
* `(3, 5) @ (5, 3)` -> `(3, 3)`

In [58]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [59]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [68]:
# Create a tensor (3, 2)
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

Since x @ y doesn't work, let's transpose y

Let's try `tf.reshape()` first

In [69]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [70]:
# Now we can x @ tf.reshape(y, shape=(2, 3))
x @ tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [71]:
# Can do the same with transpose
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [72]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [73]:
# You can achieve the same result with parameter "transpose_a" in tf.matmul
tf.matmul(a=x, b=y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

### The dot product

Multiplying matrix by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot). 

In [74]:
# Perform the dot pruduct on x & y (requires x to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

You might notice that although using both `reshape` and `tranpose` work, you get different result when using each.

Let's see an example, first with `tf.transpose()` then with `tf.reshape()`.

In [76]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

Which is strange because when dealing with `y` (a`(3*2)` matrix), reshaping to `(2, 3)` and tranposing it result in the same shape.

In [77]:
# Chack shape of y, reshape y and transposed y
y.shape, tf.reshape(y, shape=(2, 3)).shape, tf.transpose(y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [79]:
# Check values of y, reshape y and transposed y
print("Normal Y:")
print(y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


As you can see, the outputs of `tf.reshape()` and `tf.transpose()` when called on `y`, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the [`perm` parameter](https://www.tensorflow.org/api_docs/python/tf/transpose).

So which should you use?

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

### Matrix multiplication tidbits
* If we transposed `Y`, it would be represented as $\mathbf{Y}^\mathsf{T}$ (note the capital T for tranpose).
* Get an illustrative view of matrix multiplication [by Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html).
* Try a hands-on demo of matrix multiplcation: http://matrixmultiplication.xyz/ (shown below).

![visual demo of matrix multiplication](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-matrix-multiply-crop.gif)

### Changing the datatpe of a tensor

This is common when you want to compute using less precision (eg. 16b-it floating point numbers vs. 32-bit floating point numbers).

You can change datatype of a tensor using [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [80]:
# Create a new tensor with default datatype (float32)
b = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
c = tf.constant([1, 7])

b, c

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [81]:
# Change from float32 to float16 (reduced precision)
b = tf.cast(b, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [82]:
# Change from int32 to float32
c = tf.cast(c, dtype=tf.float32)
c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Getting the absolute value

Sometimes we want the absolute values (all values are positive) of elements in your tensors.

To do sp, you can use [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [83]:
# Create a tensor with negative values
d = tf.constant([-7, -10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [84]:
# Get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### Finding the min, max mean, sum (aggregation)

To do so, aggregation methods typically have syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.

In [85]:
# Create a tensor with 50 random values between 0 - 100
e = tf.constant(np.random.randint(0, 100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([58, 55, 86, 70, 44, 29, 31, 68, 63, 70, 91, 57, 51, 92, 71,  7, 77,
       86, 77, 18, 44, 52, 67, 44, 59,  9, 73, 46, 47, 63, 93, 65, 45,  2,
       22, 51, 59, 81, 41, 21, 22, 47, 43, 47, 70,  1, 95, 33, 62, 16])>

In [86]:
# Find the min number
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [87]:
# Find the max number
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [88]:
# Find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [89]:
# Find the sum of the all numbers
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int32, numpy=2621>

### Finding the positional maximum and minimum



In [90]:
# Create a tensor with 50 values between 0 to 1
f = tf.constant(np.random.random(50))
f

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.46001525, 0.68518733, 0.1319185 , 0.36150195, 0.51167825,
       0.90944673, 0.31262792, 0.04262003, 0.86976349, 0.10601789,
       0.36712344, 0.87594071, 0.4803231 , 0.19667319, 0.82422946,
       0.27052986, 0.03405132, 0.28414707, 0.67653922, 0.43850721,
       0.17627507, 0.19408828, 0.33375578, 0.44281686, 0.34921478,
       0.33645981, 0.28081681, 0.76679292, 0.60405033, 0.46513976,
       0.73839848, 0.16174158, 0.17087662, 0.81904201, 0.21948157,
       0.63135955, 0.40833222, 0.65028265, 0.10528279, 0.69767094,
       0.70560481, 0.65670803, 0.46117258, 0.84726274, 0.28655357,
       0.05925371, 0.3802983 , 0.09697597, 0.98509126, 0.51566979])>

In [91]:
# Find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [92]:
# Find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [96]:
# Find the maximum element position of f
print(f"The maximum value of f is at position: {tf.argmax(f).numpy()}")
print(f"The maximum value of f is: {tf.reduce_max(f).numpy()}")
print(f"Using tf.argmax() to index f, the maximum value of f is: {f[tf.argmax(f)].numpy()}")
print(f"Are the two max values the same (they should be)? {f[tf.argmax(f)].numpy() == tf.reduce_max(f).numpy()}")

The maximum value of f is at position: 48
The maximum value of f is: 0.9850912637845938
Using tf.argmax() to index f, the maximum value of f is: 0.9850912637845938
Are the two max values the same (they should be)? True


### Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimension from a tensor (dimension with size 1), you can use `tf.squeeze()`.

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

In [99]:
# Create rank 5 tensor with 50 values between 0 - 100
g = tf.constant(np.random.randint(0, 100, size=50), shape=(1, 1, 1, 1, 50))
g.shape, g.ndim
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
array([[[[[92, 58, 84,  5, 79, 94, 95, 46, 18, 49, 49, 78, 56, 82, 16,
           92, 33, 86, 81, 55, 33, 51, 23,  7, 54,  6, 85, 46, 96, 36,
            2, 11, 25, 20, 78,  2, 39, 61, 62, 83, 15, 21,  8, 60, 21,
           48, 61, 82, 97, 85]]]]])>

In [101]:
# Squeeze the tensor (remove all 1 dimensions)
g_squeezed = tf.squeeze(g)
g_squeezed.shape, g_squeezed.ndim
g_squeezed

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([92, 58, 84,  5, 79, 94, 95, 46, 18, 49, 49, 78, 56, 82, 16, 92, 33,
       86, 81, 55, 33, 51, 23,  7, 54,  6, 85, 46, 96, 36,  2, 11, 25, 20,
       78,  2, 39, 61, 62, 83, 15, 21,  8, 60, 21, 48, 61, 82, 97, 85])>